### ISSUE TITLE
Sparticles in absolute positione div

### ISSUE THREAD

**Issue by Air-Sidney** [simeydotme/sparticles#5]
How I understand Sparticles can calculate width and height of target div has absolute position.  I can setup width in pixels but I need widht 100%, height 100%

**Comment by simeydotme** [comment]
https://github.com/simeydotme/sparticles#styling
```css
.sparticles-container {
  position: fixed; /* or absolute */
  left: 0; right: 0;
  top: 0; bottom: 0;
  /**
   * z-index: -1; this makes the <body> still interactive 
   * by placing the sparticles behind the content
   */
  z-index: -1; 
}
```
